routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Mail;

Route::get('/', 'Admin\DashboardController@index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/call', 'VoiceController@index');
Route::post('/call', 'VoiceController@initiateCall')->name('initiate_call');

Route::get('stripe', 'StripePaymentController@stripe');
Route::post('stripe', 'StripePaymentController@stripePost')->name('stripe.post');
Route::get('notification', 'API\OrdersController@testnotification');
Route::get('agreement-document/{type}', 'Admin\DashboardController@agreement_document');
Route::get('text', 'Admin\DashboardController@text');
Route::get('check-mail/{email}', 'Front\UsersController@check_mail');
Route::get('account-confirmation', 'Front\UsersController@accountConfirmation');

Route::get('/create-connect', 'Front\StripeConnectController@createConnect')->name('create-connect');
Route::get('/create-connect-success', 'Front\StripeConnectController@createConnectSuccess')->name('create-connect-success');
Route::get('privacy-policy', 'Front\UsersController@privacy_policy');
Route::get('terms-and-condition', 'Front\UsersController@terms_and_condition');

Route::get('braintree','PaymentController@checkout');
Route::post('braintree','PaymentController@checkout');
Route::get('adyen','PaymentController@adyen');

Route::get('dwolla','PaymentController@dwolla');
Route::post('dwolla-redirect','PaymentController@dwolla_redirect');
Route::get('dwolla-callback','PaymentController@dwolla_callback');


Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {

    Route::get('/dashboard', 'DashboardController@index')->name('admin.dashboard');
    Route::get('/profile', 'AdminController@profile')->name('admin.profile');
    Route::post('/update-profile', 'AdminController@updateProfile')->name('admin.update.profile');
    Route::get('/change-password', 'AdminController@changePassword')->name('admin.change.password');
    Route::post('/update-password', 'AdminController@updatePassword')->name('admin.update.password');

    Route::get('/user-list', 'UsersController@index')->name('admin.user.list');
    Route::get('/user-active/{id}', 'UsersController@active')->name('admin.user.active');
    Route::get('/user-inactive/{id}', 'UsersController@inActive')->name('admin.user.inactive');
    Route::get('/user-detail/{id}', 'UsersController@detail')->name('admin.user.detail');



    //CMS Routes
    Route::get('/cms', 'CmsController@index')->name('admin.cms.index');
    Route::get('/cms-active/{id}', 'CmsController@active')->name('admin.cms.active');
    Route::get('/cms-inactive/{id}', 'CmsController@inActive')->name('admin.cms.inactive');
    Route::get('/cms/edit/{id}', 'CmsController@edit')->name('admin.cms.edit');
    Route::get('/cms/create', 'CmsController@create')->name('admin.cms.create');
    Route::put('/cms-update/{id}', 'CmsController@update')->name('admin.cms.update');
    Route::post('/cms-store', 'CmsController@store')->name('admin.cms.store');
    Route::get('/cms-detail/{id}', 'CmsController@detail')->name('admin.cms.detail');
    Route::get('/cms-detail/{id}', 'CmsController@detail')->name('admin.cms.detail');

    // Vendors Routes
    Route::get('/vendor-list', 'VendorsController@index')->name('admin.vendor.list');
    Route::get('/vendor-active/{id}', 'VendorsController@active')->name('admin.vendor.active');
    Route::get('/vendor-inactive/{id}', 'VendorsController@inActive')->name('admin.vendor.inactive');
    Route::get('/vendor-detail/{id}', 'VendorsController@detail')->name('admin.vendor.detail');
    Route::get('/vendor-agreement/{id}', 'VendorsController@vendor_agreement')->name('admin.vendor.agreement');


    // Drivers Routes
    Route::get('/driver-list', 'DriversController@index')->name('admin.driver.list');
    Route::get('/driver-active/{id}', 'DriversController@active')->name('admin.driver.active');
    Route::get('/driver-inactive/{id}', 'DriversController@inActive')->name('admin.driver.inactive');
    Route::get('/driver-detail/{id}', 'DriversController@detail')->name('admin.driver.detail');
    Route::get('/driver-agreement/{id}', 'DriversController@driver_agreement')->name('admin.driver.agreement');

    //Categories Routes
    Route::resource('categories', 'CategoriesController');
    Route::get('categories', 'CategoriesController@index')->name('admin.categories');
    Route::put('categories/update/{id}', 'CategoriesController@update')->name('admin.categories.update');
    Route::post('categories/store', 'CategoriesController@store')->name('admin.categories.store');
    Route::get('category-list', 'CategoriesController@index')->name('admin.categories.list');
    Route::get('category-active/{id}', 'CategoriesController@active')->name('admin.categories.active');
    Route::get('category-inactive/{id}', 'CategoriesController@inActive')->name('admin.categories.inactive');

    //Items Routes
    Route::resource('items', 'ItemsController');
    Route::get('items', 'ItemsController@index')->name('admin.items');

    // Orders Routes
    Route::resource('orders', 'OrdersController');

    //User Groups

    Route::get('/user-group', 'UserGroupController@index')->name('admin.user-group');
    Route::get('user-group-list', 'UserGroupController@index')->name('admin.user-groups.list');
    Route::get('/user-group/{id}/members', 'UserGroupController@members')->name('admin.user-groups.members');
    Route::get('/user-group/{id}/polls', 'UserGroupController@polls')->name('admin.user-groups.polls');

    Route::resource('walletpercentage', 'WalletPercentageController');
    Route::get('walletpercentage-active/{id}', 'WalletPercentageController@active')->name('admin.walletpercentage.active');
    Route::get('walletpercentage-inactive/{id}', 'WalletPercentageController@inActive')->name('admin.walletpercentage.inactive');
    Route::get('/settings', 'SettingController@settings')->name('admin.settings');
    Route::post('/settings', 'SettingController@settingsUpdate')->name('admin.settings');
});

Route::get('sendmail', function () {
    $data = array(
        'bodyMessage' => "hello trilok"
    );

    Mail::send('mail', $data, function ($message) {
        $message->to('trilokkumar970@gmail.com')->subject('Just Laravel demo email using SendGrid');
    });

    return 'done ';
});

app/Models/Driver.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\User;

class Driver extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'driver_details';

    public function getDrivingLicenceExpiryDateAttribute($value)
    {
        return date("Y/m/d", strtotime($value)); 
    }
    
    public function getVehicleRegistrationExpiryDateAttribute($value)
    {
        return date("Y/m/d", strtotime($value)); 
    }
    
    public function getVehicleInsuranceExpiryDateAttribute($value)
    {
        return date("Y/m/d", strtotime($value)); 
    }
    
    public function getVehicleYearAttribute($value)
    {
        return date("Y", strtotime($value)); 
    }

    public static function getDriverModel($limit, $offset, $search, $orderby,$order)
    {
        $orderby  = $orderby ? $orderby : 'id';
        $order    = $order ? $order : 'desc';

        $q        = User::where('role','driver')->orderBy('created_at', 'desc');
        
        if($search && !empty($search)){
            $q->where(function($query) use ($search) {
                $query->orWhere('email', 'LIKE', $search.'%');
                $query->orWhere('user_name', 'LIKE', $search.'%');
                $query->orWhere('mobile_number', 'LIKE', $search.'%');
                $query->orWhere('city', 'LIKE', $search.'%');
                $query->orWhere('state', 'LIKE', $search.'%');
                $query->orWhere('address', 'LIKE', $search.'%');
            });
        }

        $response   =   $q->orderBy($orderby, $order)
                            ->offset($offset)
                            ->limit($limit)
                            ->get();

        $response   =   json_decode(json_encode($response));
        return $response;
    }

    public function user(){
        return $this->belongsTo(User::class, 'user_id');
    }

    
}

app/Http/Controllers/Admin/DriversController.php
<?php
namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use Validator;
use App\User;
use App\Models\Driver;

class DriversController extends Controller
{

	public function __construct()
    {
        $this->sortable_columns = [
            0 => 'id',
            1 => 'user_name',
            2 => 'email',
            3 => 'mobile_number',
            4 => 'address',
            5 => 'role',
        ];
    }

	public function index(Request $request) {
		if($request->ajax())
        {
            $totalCms       = Driver::count();
            $limit          = $request->input('length');
            $start          = $request->input('start');
            $search         = $request['search']['value'];
            $orderby        = $request['order']['0']['column'];
            $order          = $orderby != "" ? $request['order']['0']['dir'] : "";
            $draw           = $request['draw'];

            $response       = Driver::getDriverModel($limit , $start , $search, $this->sortable_columns[$orderby], $order);

            if(!$response){
                $page       = [];
                $paging     = [];
            }
            else{
                $page       = $response;
                $paging     = $response;
            }

            $data = array();

            foreach ($page as $driver) {
            	$u['id']            = ($driver->id);
                $u['user_name']     = ucwords($driver->user_name);
                $u['email']         = ($driver->email);
                $u['mobile_number'] = '+'.$driver->country_code .'-' . ($driver->mobile_number);
                $u['address']       = ($driver->address);
                $u['role']          = (ucfirst($driver->role));
                $u['created_at']    = date('d/m/Y', strtotime($driver->created_at));

                $status             = view('admin.drivers.status', ['id' => $driver->id, 'status' => $driver->status]);
                $u['status']        = $status->render();

                $actions            = view('admin.drivers.actions', ['id' => $driver->id, 'status' => $driver->status]);

                $u['actions']       = $actions->render();

                $data[] = $u;

                unset($u);
            }

            $return = [
                "draw"              =>  intval($draw),
                "recordsFiltered"   =>  intval( $totalCms),
                "recordsTotal"      =>  intval( $totalCms),
                "data"              =>  $data
            ];
            return $return;
        }

		$page_title = 'Drivers List';
        return view('admin.drivers.index', compact('page_title'));
	}

	/**
     * Active
     *
     * @param  int  $id
     */
    public function active($id)
    {
        $driver = User::find($id);
        $driver->status = '1';
        $driver->save();

        return response()->json(array('success' => true));
    }

    /**
     * In-Active
     *
     * @param  int  $id
     */
    public function inActive($id)
    {
        $driver = User::find($id);
        $driver->status = '0';
        $driver->save();

        return response()->json(array('success' => true));
    }

    public function detail($id) {
		$page_title = 'Driver Detail';
        $driver = User::where('id',$id)->with('driver')->first();

        return view('admin.drivers.detail', compact('page_title', 'driver'));
    }
    public function driver_agreement($id)
    {
        $user = User::find($id);
        $page_title = 'Driver Agreement Document';


        try {
            $mpdf = new \Mpdf\Mpdf([
              'tempDir' => __DIR__ . '/../tmp', // uses the current directory's parent "tmp" subfolder
              'setAutoTopMargin' => 'stretch',
              'setAutoBottomMargin' => 'stretch'
            ]);

        $html = view('admin.drivers.driver-agreement', compact('user','page_title'))->render();


        $mpdf->WriteHTML($html);
        $mpdf->Output();
          } catch (\Mpdf\MpdfException $e) {
              print "Creating an mPDF object failed with" . $e->getMessage();
          }
    }
/////////////////////////////////////////////////////////////////////
}

resources/views/admin/drivers/actions.blade.php
<a class="btn btn-info btn-xs" href="{{ url('admin/driver-agreement',$id)}}" data-toggle="tooltip" title="Agreement" >
<i class="far fa-file-pdf"></i>
</a>
<a class="btn btn-primary btn-xs" href="{{ url('admin/driver-detail',$id)}}" data-toggle="tooltip" title="View">
<i class="far fa-eye"></i>
</a>

@if($status == 0)
<a class="btn btn-success btn-xs active-button" href="#" data-id="{{ $id }}" >
  Active
</a>

@else
<a class="btn btn-danger btn-xs inactive-button" href="#" data-id="{{ $id }}">
  In Active
</a>
@endif

resources/views/admin/drivers/detail.blade.php
@extends('layouts.admin')

@section('content')
<?php

  // echo "<pre>";
  // print_r($driver);
  // die;
?>

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">{{ $page_title }}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
              <li class="breadcrumb-item active">{{ $page_title }}</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="row">
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
              <h3 class="card-title">{{ $page_title }} # {{ $driver->user_name }}</h3>
              </div>
              <div class="card-body">
                  <div class="table-responsive">
                    <table class="table">
                      <tr>
                        <th style="width:25%">Username:</th>
                        <td>{{ ucfirst($driver->user_name) }}</td>
                      </tr>
                      <tr>
                        <th>Email</th>
                        <td>{{ $driver->email }}</td>
                      </tr>
                      <tr>
                        <th>Mobile No.:</th>
                        <td>{{ $driver->country_code }}-{{ $driver->mobile_number }}</td>
                      </tr>
                      <tr>
                        <th>Dob:</th>
                        <td>{{ date("d-m-Y",strtotime($driver->dob)) }}</td>
                      </tr>
                      <tr>
                        <th>SSN:</th>
                        <td>{{ $driver->ssn }}</td>
                      </tr>
                      <tr>
                        <th>Address:</th>
                        <td>{{ $driver->address }}</td>
                      </tr>
                      <tr>
                        <th>City:</th>
                        <td>{{ ucfirst($driver->city) }}</td>
                      </tr>
                      <tr>
                        <th>State:</th>
                        <td>{{ ucfirst($driver->state) }}</td>
                      </tr>
                      @if($driver->driver)
                        <tr>
                          <th>Zip:</th>
                          <td>{{ ($driver->zip) }}</td>
                        </tr>
                      @endif
                      <tr>
                        <th>Profile Picture:</th>
                        <td>
                          @if($driver->profile_picture)
                          <div class="widget-user-image">
                            <a href="{{ url($driver->profile_picture) }}" target="_blank">
                              <img class="img-circle elevation-2 img-lg" src="{{ asset($driver->profile_picture) }}" alt="{{ $driver->user_name }}">
                            </a>

                          </div>
                          @endif
                        </td>
                      </tr>
                      <tr>
                        <th>Status:</th>
                        <td>
                          @if($driver->status == 1)
                          <span class="badge badge-success">Active</span>
                          @else
                          <span class="badge badge-danger">In Active</span>
                          @endif
                        </td>
                      </tr>
                    </table>
                  </div>
              </div>
            </div>
          </div>

          @if($driver->driver)
          <div class="col-md-12">
            <div class="card">
              <div class="card-header">
              <h3 class="card-title">{{ $page_title }} # {{ $driver->user_name }}</h3>
              </div>
              <div class="card-body">
                  <div class="table-responsive">

                    <table class="table">

                        <tr>
                            <th style="width:25%">Id:</th>
                            <td>{{ ucfirst($driver->driver->id) }}</td>
                        </tr>
                        <tr>
                            <th style="width:25%">Driver Code:</th>
                            <td>{{ ucfirst($driver->driver->driver_code) }}</td>
                          </tr>
                        <tr>
                          <th style="width:25%">Name:</th>
                          <td>{{ ucfirst($driver->driver->name) }}</td>
                        </tr>

                        <tr>
                        <th>Address : </th>
                        <td>{{ $driver->driver->address }}</td>
                        </tr>

                        <tr>
                          <th>Driving Licence Number:</th>
                          <td>{{ $driver->driver->driving_licence_number }}</td>
                        </tr>

                        <tr>
                          <th>Driving Licence Expiry Date:</th>
                          <td>{{ $driver->driver->driving_licence_expiry_date }}</td>
                        </tr>

                        <tr>
                          <th>Driving Licence Picture:</th>
                          <td>
                            @if($driver->driver->driving_licence_image)
                            <div class="widget-user-image">
                              <a href="{{ url($driver->driver->driving_licence_image) }}" target="_blank">
                                <img class="img-thumbnail elevation-2 img-lg" src="{{ asset($driver->driver->driving_licence_image) }}" alt="{{ $driver->driver->name }}">
                              </a>
                            </div>
                            @endif
                          </td>
                        </tr>

                        <tr>
                          <th>Vehicle Registration Number:</th>
                          <td>{{ ($driver->driver->vehicle_registration_number) }}</td>
                        </tr>

                        <tr>
                          <th>Vehicle Registration Expiry:</th>
                          <td>{{ ($driver->driver->vehicle_registration_expiry_date) }}</td>
                        </tr>

                        <tr>
                          <th>Vehicle Registration Picture:</th>
                          <td>
                            @if($driver->driver->vehicle_registration_image)
                            <div class="widget-user-image">
                              <a href="{{ url($driver->driver->vehicle_registration_image) }}" target="_blank">
                                <img class="img-thumbnail elevation-2 img-lg" src="{{ asset($driver->driver->vehicle_registration_image) }}" alt="{{ $driver->driver->name }}">
                              </a>
                            </div>
                            @endif
                          </td>
                        </tr>

                        <tr>
                          <th>Vehicle Insurance Number:</th>
                          <td>{{ ($driver->driver->vehicle_insurance_number) }}</td>
                        </tr>

                        <tr>
                          <th>Vehicle Insurance Expiry:</th>
                          <td>{{ ($driver->driver->vehicle_insurance_expiry_date) }}</td>
                        </tr>

                        <tr>
                          <th>Vehicle Insurance Picture:</th>
                          <td>
                            @if($driver->driver->vehicle_insurance_image)
                            <div class="widget-user-image">
                              <a href="{{ url($driver->driver->vehicle_insurance_image) }}" target="_blank">
                                <img class="img-thumbnail elevation-2 img-lg" src="{{ asset($driver->driver->vehicle_insurance_image) }}" alt="{{ $driver->driver->name }}">
                              </a>
                            </div>
                            @endif
                          </td>
                        </tr>

                        <tr>
                          <th>Vehicle Make:</th>
                          <td>{{ ($driver->driver->vehicle_make) }}</td>
                        </tr>

                        <tr>
                          <th>Vehicle Model:</th>
                          <td>{{ ($driver->driver->vehicle_model) }}</td>
                        </tr>

                        <tr>
                          <th>Vehicle Year:</th>
                          <td>{{ ($driver->driver->vehicle_year) }}</td>
                        </tr>

                        <tr>
                          <th>Vehicle Color:</th>
                          <td>{{ ($driver->driver->vehicle_color) }}</td>
                        </tr>

                    </table>

                  </div>
              </div>
            </div>
          </div>
          @endif
      </div>

    </section>
    <!-- /.content -->
  </div>
@endsection

@section('styles')

@endsection

@section('scripts')

<script type="text/javascript">
$(document).ready(function () {



});
</script>
@endsection

resources/views/admin/drivers/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">{{ $page_title }}</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Home</a></li>
              <li class="breadcrumb-item active">{{ $page_title }}</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="row">
        <div class="col-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">{{ $page_title }}</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body">
              <table id="userTable" class="table table-bordered table-hover">
                <thead>
                <tr>
                  <th width="5%">S.NO</th>
                  <th>Username</th>
                  <th>Email</th>
                  <th>Mobile No.</th>
                  <th>Address</th>
                  <th>Role</th>
                  <th>Created</th>
                  <th width="5%">Status</th>
                  <th width="10%">Action</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- /.content -->
  </div>
@endsection

@section('styles')
<!-- DataTables -->
  <link rel="stylesheet" href="{{ asset('public/admin/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css') }}">
  <link rel="stylesheet" href="{{ asset('public/admin/plugins/datatables-responsive/css/responsive.bootstrap4.min.css') }}">
  <link data-require="sweet-alert@*" data-semver="0.4.2" rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
@endsection

@section('scripts')
<!-- Bootstrap 4 -->
<script src="{{ asset('public/admin/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- DataTables -->
<script src="{{ asset('public/admin/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('public/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('public/admin/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}"></script>
<script src="{{ asset('public/admin/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

<script type="text/javascript">
$(document).ready(function () {
  
  $('#userTable').DataTable({
        "bProcessing": true,
        "serverSide": true,
        "ajax":{
            url :"{{ url('admin/driver-list') }}",
            
            error: function(){  
                alert('Something went wrong');
            }
        },
        "aoColumns": [
            { mData: 'id', orderable: false,
            render: function (data, type, row, meta) {
                return meta.row + meta.settings._iDisplayStart + 1;
            }},
            { mData: 'user_name' },
            { mData: 'email' },
            { mData: 'mobile_number' },
            { mData: 'address' },
            { mData: 'role' },
            { mData: 'created_at', orderable: false },
            { mData: 'status', orderable: false },
            { mData: 'actions', orderable: false },
        ],
        "aoColumnDefs": [
          { "bSortable": false, "aTargets": ['action'] }
        ]
    });

  /** Active Admin **/
        $("#userTable").on('click','.active-button',function(){
            user_id = $(this).attr('data-id');
            swal({
              title: "Are you sure you want to active this?",
              icon: "success",
              buttons: [
                'No, cancel it!',
                'Yes, I am sure!'
              ],
              dangerMode: false,
            }).then(function(isConfirm) {
              if (isConfirm) {
                $.ajax({
                       url:"{{ url('/admin/driver-active') }}" +"/"+user_id,
                       success:function(data)
                       {
                        setTimeout(function(){
                         $('#userTable').DataTable().ajax.reload();
                        }, 1000);
                       }
                      });
              } 
            });
        });
        

        /** Inactive Admin **/
        $("#userTable").on('click','.inactive-button',function(){
            user_id = $(this).attr('data-id');
            // alert(user_id)
            swal({
              title: "Are you sure you want to inactive this?",
              icon: "warning",
              buttons: [
                'No, cancel it!',
                'Yes, I am sure!'
              ],
              dangerMode: false,
            }).then(function(isConfirm) {
              if (isConfirm) {
                $.ajax({
                       url:"{{ url('admin/driver-inactive') }}" +"/"+user_id,
                       success:function(data)
                       {
                        setTimeout(function(){
                         $('#userTable').DataTable().ajax.reload();
                        }, 1000);
                       }
                      });
              } 
            });
        });
  
});
</script>
@endsection

resources/views/admin/drivers/status.blade.php
@if($status == 1)
<span class="badge badge-success">Active</span>
@else
<span class="badge badge-danger">In Active</span>
@endif